package com.leandroftm.game_library_api.exception.Enum;

public enum ErrorCode {
    UNEXPECTED_ERROR,
    VALIDATION_EXCEPTION,
    INVALID_CREDENTIALS,
    CONFLICT,
    BAD_REQUEST,
    NOT_FOUND,
    USER_ALREADY_ACTIVE,
    USER_ALREADY_INACTIVE,
    GAME_STATUS_ALREADY_PLAYING,
    GAME_STATUS_ALREADY_DROPPED,
    GAME_STATUS_IS_NOT_PLAYING,
    GAME_ALREADY_FAVORITE,
    GAME_ALREADY_NOT_FAVORITE
}
