package com.leandroftm.game_library_api.exception.Enum;

public enum ErrorCode {
    UNEXPECTED_ERROR,
    VALIDATION_EXCEPTION,
    INVALID_CREDENTIALS,
    CONFLICT,
    BAD_REQUEST,
    NOT_FOUND,
    USER_NOT_FOUND,
    USER_ALREADY_ACTIVE,
    USER_ALREADY_INACTIVE,
    USER_NAME_ALREADY_EXISTS,
    USER_EMAIL_ALREADY_EXISTS,
    USER_PASSWORD_CONFLICT,
    GAME_NOT_FOUND,
    DUPLICATED_GAME_STATUS,
    INVALID_GAME_STATUS,
    COMPLETED_GAME_CANNOT_BE_DROPPED,
    GAME_ALREADY_EXISTS,
    GAME_STATUS_ALREADY_PLAYING,
    GAME_STATUS_ALREADY_DROPPED,
    GAME_STATUS_IS_NOT_PLAYING,
    GAME_ALREADY_FAVORITE,
    GAME_ALREADY_NOT_FAVORITE,
    IGDB_GAME_NOT_FOUND
}
