ALTER TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    igdb_id        BIGINT       NOT NULL,
    game_name      VARCHAR(255) NOT NULL,
    favorite       BOOLEAN      NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    start_date     TIMESTAMP,
    completed_date TIMESTAMP,
    status         VARCHAR(30),
    user_id        BIGINT,

    CONSTRAINT  uk_user_game UNIQUE (user_id, igdb_id),
    CONSTRAINT fk_user_games_users FOREIGN KEY (user_id) REFERENCES users (id)
);